[package]
name = "tgar_bot_http"

authors.workspace = true
version.workspace = true
rust-version.workspace = true
edition.workspace = true
description.workspace = true

[dependencies]
actix-web.workspace = true
futures = "0.3.31"
mongodb.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
tgar_bot_mongodb.path = "../tgar_bot_mongodb"
tgar_bot_utils.path = "../tgar_bot_utils"
tracing.workspace = true
tracing-actix-web.workspace = true
